---
branch: release
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/exec"
  -
    - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
  -
    - "@semantic-release/github"
    - assets: ["docs-*.tar.xz"]
  -
    - "@semantic-release/exec"
    - prepareCmd: "make docs-${nextRelease.version}.tar.xz"
