name: docs

on: push

jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache Gems
      id: cache-gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems

    - name: Build Gems
      if: steps.cache-gems.outputs.cache-hit != 'true'
      run: bundle install --deployment

    - name: build docs
      run: make docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
