name: docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache gems
      id: cache-gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems

    - name: Bundle config
      run: |-
        mkdir -p .bundle
        cat <<EOF > .bundle/config
        ---
        BUNDLE_FROZEN: "true"
        BUNDLE_PATH: "vendor/bundle"
        EOF

    - name: Build gems
      if: steps.cache-gems.outputs.cache-hit != 'true'
      run: bundle install --deployment

    - name: build docs
      run: make docs

    - name: Deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
        SCRIPT_MODE: true
      run: |-
        set -euxo pipefail
        wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        bash ./entrypoint.sh
      with:
        keepFiles: true
