name: test-linux
on: push
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |-
        set -euxo pipefail
        swift build
    - name: Run tests
      run: |-
        set -euxo pipefail
        swift test
