name: tests

on: push

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    - name: Generate coverage
      run: make coverage.lcov
    - name: Upload coverage
      run: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
